Cargo.lock, sugondat-chain/pallets/blobs/Cargo.toml, sugondat-chain/pallets/blobs/src/lib.rs, sugondat-chain/pallets/blobs/src/namespace_param.rs, sugondat-chain/pallets/blobs/src/tests.rs, sugondat-chain/primitives/Cargo.toml, sugondat-chain/primitives/src/lib.rs, sugondat-nmt/src/lib.rs, sugondat-nmt/src/ns.rs, sugondat-nmt/src/root.rs, sugondat-nmt/src/tests.rs, sugondat-nmt/src/tree.rs
Also updates the transaction validation logic to reject transactions with invalid namespaces.
Closes #12
=> Use 16 byte namespaces, introduce wrapper type for pallet parameter

sugondat-chain/node/src/command.rs, sugondat-chain/pallets/blobs/src/mock.rs, sugondat-chain/runtimes/sugondat-kusama/Cargo.toml, sugondat-shim/src/cli.rs, sugondat-shim/src/sugondat_rpc/conn.rs
=> chore: update the repo URL

sugondat-shim/src/sugondat_rpc/conn.rs
without this, the message would say
WARN_WRONG_VERSION="connected to a sugondat node with a newer runtime than the one this shim was compiled against. Update the shim lest you run into problems. https://github.com/thrumdev/sugondat"
=> shim: update the wrong version message

README.md
During testing I realized that the instruction for reseting chain state is incorrect. This change fixes it.
=> chore: fix instruction for reseting state of gm

.github/workflows/ci.yml
Related #120 
The build will initially fail. It's necessary to register a self-hosted runner in the repo settings first as described here: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository
=> Switching to self-hosted runner.

.github/workflows/ci.yml, docker/gha-runner.Dockerfile
Customize the docker image for use on the self-hosted GHA runner.
This allows us to elide installation steps from the CI workflow and
enables us using a shared cache for builds.
=> ci: use gha-runner image

Cargo.toml
it's mostly useless anyway, but could be overriden if needed. OTOH, it improves the build times and reduces the artifact sizes significantly which is very important in our case.
=> build: turn off debug-info

Cargo.lock, Cargo.toml, sugondat-chain/node/Cargo.toml
Closes #139
I've verified that rococo-runtime is not built. However, rococo-runtime-constants
are still built. Running `cargo tree` confirms the observation, `rococo-runtime` is
not in tree and `rococo-runtime-constants` is.
The changes of Cargo.lock are a bit confusing though, because it's actually the opposite:
-constants is removed and rococo-runtime still is present.
I've also verified that the sovereign demo works.
=> build: remove rococo-native from the build

sugondat-chain/node/src/cli.rs, sugondat-chain/node/src/command.rs, sugondat-chain/node/src/command/export_genesis_metadata.rs
This commit adds a new subcommand to the CLI that exports metadata from
the compiled-in runtime, similar to the existing subcommands like
`export-genesis-state` and `export-genesis-wasm`.
A typical usage would be
```bash
sugondat-node export-genesis-metadata --raw binary_metadata.scale
subxt codegen --file binary_metadata.scale | \
rustfmt --edition=2021 --emit=stdout > src/metadata.rs
```
Ideally, it would be solved by [paritytech/polkadot-sdk#2745] and thus we could
just take the wasm blob (either exported by `export-genesis-wasm`) and just get
it from there via simple of the shelf tools. Until then, we will have this command.
Closes #142 
[paritytech/polkadot-sdk#2745]: https://github.com/paritytech/polkadot-sdk/issues/2745
=> node/cli: export genesis metadata

Cargo.lock, sugondat-chain/primitives/src/lib.rs, sugondat-chain/runtimes/sugondat-kusama/Cargo.toml, sugondat-chain/runtimes/sugondat-kusama/src/constants.rs, sugondat-chain/runtimes/sugondat-kusama/src/lib.rs, sugondat-chain/runtimes/sugondat-kusama/tests/integration_test.rs
This PR contains an implementation of the following formula for fees:
```
inclusion_fee = base_fee + [targeted_length_fee_adjustment * length_fee] + [targeted_weight_fee_adjustment * weight_fee];
```
This is accomplished by using `LengthToFee` dynamically along with `FeeMultiplierUpdate`.
Decoupling `length_fee` and `weight_fee` could be the perfect solution to handle both blockchain usage congestion and blocks usage.
In #16, I explain how difficult it is to find a relationship between those two. The main difference is that each `submit_blob` extrinsic has a weight even with a blob of zero size.
Having two adjustment factors can handle every scenario. Some extreme ones are:
- Very low general usage, few transactions with small blobs => both `targeted_length_fee_adjustment` and …
=> Blobs Fees Adjustments

sugondat-chain/runtimes/sugondat-kusama/src/fee_adjustment.rs, sugondat-chain/runtimes/sugondat-kusama/src/fee_adjustment_tests.rs, sugondat-chain/runtimes/sugondat-kusama/src/lib.rs, sugondat-chain/runtimes/sugondat-kusama/tests/integration_test.rs
Tests are copied from polkadot-sdk/substrate/bin/node/runtime/impls.rs and adapted to test our struct BlobsFeeAdjustment
=> Fee Adjustment Tests

Cargo.lock, sugondat-chain/node/Cargo.toml, sugondat-chain/node/src/main.rs, sugondat-chain/node/src/proposer.rs, sugondat-chain/node/src/service.rs
This creates, but does not activate, a solution to #147.
The implementation differs from the proposed model in #147 because `UpgradeGoAhead` signals are accounted for directly, so there is no need for an intermittent heartbeat.
We cannot activate this yet because the fees logic needs to account for skipped blocks, which it currently is incapable of.
=> node: proposer for limiting blocks

sugondat/shim/src/cli.rs, sugondat/shim/src/cmd/query/block.rs, sugondat/shim/src/cmd/query/mod.rs, sugondat/shim/src/dock/rollkit.rs, sugondat/shim/src/dock/sovereign.rs, sugondat/shim/src/sugondat_rpc/mod.rs
This implements the `shim query block` subcommand. The behavior is to default to the best block, but users may query blocks by number or hash as well.
Sample output:
```
Block: #128420
Hash: 0xc5bbe678bd4b25fa15d5828610627177c36288c5cfa18b76f1bfae1176c2974b
Parent Hash: 0x46b1dbf80b848aa8c8ff1059c1d02fd0b209eac2756bdfacc70c9984a607e92e
Blobs Root: 0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Min Namespace: 0x00000000000000000000000000000000
Max Namespace: 0x00000000000000000000000000000000
Timestamp: 1703806386000
Blob Count: 0 (0 bytes)
```
I would appreciate it if we didn't review the output format too harshly in this PR, and instead adjust that in follow-ups.
=> shim: implement block query

sugondat/shim/src/cmd/query/blob.rs, sugondat/shim/src/cmd/query/block.rs
I initially felt that the 1-based indices were more human friendly, but it does conflict with the extrinsic indices being 0-based. Probably, the users are familiar enough with computers that 0-based indices will not be too confusing. For consistency with other index types, a 0-based index is preferable to me.
=> shim: print zero-based blob indices

sugondat/shim/src/cli.rs
This is a follow up for #164 that clarifies the status quo behavior
when the block is not available in the CLI docs.
=> shim/cli: clarification on behavior

sugondat/chain/node/src/proposer.rs
This behavior is useful for testing. Specifically, for simple detection of
"healthiness" of the chain just after starting up.
This change is needed to make this work  https://github.com/thrumdev/blobs/pull/190/commits/4a9f29e52d77ac676cf6a6153e99c1affbad3442#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03R38
Related #156 #157
=> node: author the first block unconditionally

adapters/sovereign/src/service.rs, adapters/sovereign/src/service/client.rs, demo/sovereign/docker/rollup_config.docker.toml
Makes it possible to configure a timeout from the rollup_config.toml. At the same time
increased the timeout for the sovereign demo.
=> adapters/sovereign: configurable timeout

demo/rollkit/init-local.sh, demo/rollkit/restart-local.sh
Set the namespace used for the gm demo that is compatible with the current
version. Specifically, the current version requires to be the version byte
(0th index) be zero and the reserved bytes (1..5th indicies) be zero as well.
=> demo/rollkit: fix the namespaces

sugondat/nmt/src/ns.rs, sugondat/shim/src/dock/rollkit.rs, sugondat/shim/src/dock/rpc_error.rs, sugondat/shim/src/dock/sovereign.rs, sugondat/shim/src/sugondat_rpc/mod.rs
This changeset is meant to improve the logging. Basically committing whatever
logging changes that I did for debugging issues with the demo.
=> chore: improve logging

adapters/sovereign/src/service.rs, adapters/sovereign/src/service/client.rs, demo/rollkit/docker/Dockerfile, demo/rollkit/init-local.sh, demo/rollkit/restart-local.sh, demo/sovereign/docker/Dockerfile, demo/sovereign/docker/rollup_config.docker.toml, docker/docker-compose.yml, sugondat/chain/Dockerfile, sugondat/chain/node/src/proposer.rs, sugondat/nmt/src/ns.rs, sugondat/shim/Dockerfile, sugondat/shim/src/dock/rollkit.rs, sugondat/shim/src/dock/rpc_error.rs, sugondat/shim/src/dock/sovereign.rs, sugondat/shim/src/sugondat_rpc/mod.rs
This commit introduces docker/docker-compose.yml. Thanks to it
you can now spin up a network with just one command:
docker compose -f docker/docker-compose.yml --build up
That will launch the polkadot localnet, the parachain node, the shim
and the demoes: gm (based on rollkit) and the sovereign demo.
Besides that this commit adds explicit cache IDs: that seems to improve
the caching behavior when running builds from docker-compose.
Atm, parity/polkadot image isn't multi-arch and doesn't support arm64.
To properly support macOS builds I opted to build the whole thing inside
amd64. It seems it has ok performance.
Also, I wrapped the docker entrypoints in tini. This solves the problem
of propagating the SIGTERM/SIGINT when stopping the services.
=> build: docker-compose

sugondat/chain/runtimes/sugondat-kusama/src/lib.rs, sugondat/chain/runtimes/sugondat-kusama/tests/fee_adjustments.rs, sugondat/chain/runtimes/test/src/lib.rs, sugondat/chain/runtimes/test/tests/fee_adjustments.rs
=> fees: min multiplier definition and testing

sugondat/shim/src/cli.rs, sugondat/shim/src/cmd/query/mod.rs, sugondat/shim/src/cmd/serve.rs, sugondat/shim/src/sugondat_rpc/conn.rs, sugondat/shim/src/sugondat_rpc/mod.rs
=> shim: add no_retry flag

sugondat/shim/src/cli.rs, sugondat/shim/src/cmd/query/blob.rs, sugondat/shim/src/cmd/query/block.rs, sugondat/shim/src/cmd/query/mod.rs, sugondat/shim/src/dock/rollkit.rs, sugondat/shim/src/dock/sovereign.rs, sugondat/shim/src/sugondat_rpc/mod.rs
Add a struct used to contain both BlockRef and the wait flag, to make it reusable for both block and blob queries (and all other possible new queries).
The struct should be used with `clap(flatten)` to make all the fields appear as options in the query command.
TODOs:
+ [x] Better naming
+ [x] Better logging
closes #171
It would also be great to add something like `wait-interval` to specify how often the request of the block should be made (in `wait_header_and_extrinsics`). Currently, I've set a two-second sleep between each call
=> shim: add wait flag

sugondat/chain/node/Cargo.toml, sugondat/chain/primitives/src/lib.rs
Just a quick fix to avoid compiling `last_relay_block_number_key` in no_std, 
this made me think, is it worth to have this function in sugondat-primitives?
it is just used once in the node proposer
=> fix sugondat-primitives not compiling in release

docker/gha-runner.Dockerfile
Wasm build in 1.6.0 seems to require this. The runner needs to be re-deployed once it's merged.
=> gh-runner: add rust-src as a component

sugondat/chain/pallets/length-fee-adjustment/src/lib.rs, sugondat/chain/pallets/length-fee-adjustment/src/mock.rs, sugondat/chain/pallets/length-fee-adjustment/src/tests.rs, sugondat/chain/runtimes/sugondat-kusama/src/lib.rs, sugondat/chain/runtimes/test/src/lib.rs
Tracking the previous relay parent number is already done by parachain system. No need to introduce a redundancy.
=> remove unnecessary storage item in length fee adjustment

sugondat/chain/node/src/cli.rs
`export-genesis-state` is needed as alias to the command ExportGenesisHead
because zombienet rely on that command
In [this](https://github.com/paritytech/polkadot-sdk/commit/8683bbeefb688364f5f9e445dffb42fc266dd8f0) commit, the change to the command was introduced, while also maintaining backward compatibility (as stated at the end of the commit message)
=> node: add alias to command ExportGenesisHead

sugondat/chain/node/src/cli.rs
The alias is no longer needed by zombienet after the following issue was solved in version 1.3.92
https://github.com/paritytech/zombienet/issues/1712#issuecomment-1924672880
=> node: remove export-genesis-state alias

.cargo/config.toml, Cargo.lock, Cargo.toml, demo/sovereign/demo-rollup/provers/risc0/guest-sugondat/Cargo.lock, xtask/Cargo.toml, xtask/src/build.rs, xtask/src/cli.rs, xtask/src/main.rs, xtask/src/shim.rs, xtask/src/sovereign.rs, xtask/src/zombienet.rs
The following PR introduces the usage of xtask for scripting tests and handling CI. It includes minimal required components for enabling sovereign rollup testing. Additional features mentioned in new issues are linked within the code and should be addressed as follow up PRs
p.s.
#[rustfmt::skip] is just my preference for avoiding multiple lines in the "cmd!" macro. If you don't agree with it or if it goes against the standard, I can remove it easily
=> ci: introducing xtask ci testing

ikura/chain/node/src/cli.rs
This is needed because of the lack of binary builds of zombienet
for macOS.
Reverts #229
=> node: reinstate `export-genesis-state`.

xtask/src/build.rs, xtask/src/cli.rs, xtask/src/logging.rs, xtask/src/main.rs, xtask/src/shim.rs, xtask/src/sovereign.rs, xtask/src/zombienet.rs
The only non-trivial thing in this PR should be how 'log_path' is specified in the CLI. I propose handling it in the following way: if 'log_path' is relative, it will be made absolute relative to the root project_path and not to where the command is actually called. Absolute paths would not been changed
closes #232
=> xtask: make testing cwd independent

Cargo.lock, Cargo.toml, xtask/Cargo.toml, xtask/src/build.rs, xtask/src/cli.rs, xtask/src/main.rs, xtask/src/zombienet.rs
Adds a new command `cargo xtask zombienet` to launch polkadot validator set and an ikura-node collator.
Useful to test changes.
Note that potentially this tool will evolve into one that launches not only zombienet but also shim. But it's for the future.
=> xtask: utility to launch zombienet

.github/workflows/ci.yml, xtask/src/cli.rs, xtask/src/main.rs
remove the ci flag and set the default behavior to add binaries to the path and CONSTANTS_MANIFEST to environment variables
=> xtask: add no_infer_bin_path flag

Cargo.lock, Cargo.toml, xtask/Cargo.toml, xtask/src/build.rs, xtask/src/logging.rs, xtask/src/main.rs, xtask/src/shim.rs, xtask/src/sovereign.rs, xtask/src/zombienet.rs
Duct exhibits too many peculiar behaviors: 
- Regarding how it deals with relative paths, it seems that the spawned process assumes a position in the file system relative to where the parent process was spawned, not where the child process was spawned.
- You cannot use the same opened file in multiple commands because they take ownership of the file descriptor and close it once the command finishes.
- If you capture stderr to print it later but the command fails with a non-zero status code, it will drop the stderr and return an empty enum. Stdout and stderr are only returned if the command terminates correctly.
- There is no way to convert `duct::Cmd` to a `std::process::Command` that is needed to deal with process group IDs.
That's why I am moving to `xshell.` However, it does not handle …
=> xtask: migrating from duct to xshell

README.md
Update the README.md after #260
=> chore: update readme after removing the adapter
